version: '3.8'
services:
  vitepress:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
        - /app/node_modules
    command: yarn run dev